apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-gradle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi
