apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/azure-load-balancer-type: nlb
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: jenkins
  namespace: jenkins
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 10.5.0.200
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: agent
    port: 50000
    protocol: TCP
  selector:
    app: jenkins
  type: LoadBalancer