apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  namespace: jenkins
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - mountPath: /tmp/storage
      name: jenkins-home
  volumes:
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: azurefile
